mybatis:
  type-aliases-package: com.ming.demo.model

spring:
  datasource:
    url: jdbc:mysql://cdb-1yfd1mlm.cd.tencentcdb.com:10056/dindangci
    username: root
    password: ABCcba20170607
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
swagger:
  base-path: /**
  base-package: 'com.ming'
  title: 'spring-boot-swagger-demo'
  description: '基于Swagger构建的SpringBoot RESTApi 文档'
  version: '1.0'
  contact:
    name: '空夜'
    url: 'http://www.eknown.cn'
    email: 'eknown@163.com'